name: Deploy Ionic PWA

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Node.js dan install dependencies
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      # Build aplikasi Ionic PWA
      - name: Build Ionic PWA
        run: |
          npm run build
        env:
          CI: true

      # Upload hasil build ke server dengan FTP
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/  # Folder hasil build Ionic
          server-dir: /  # Sesuaikan dengan direktori server Anda
